---
apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: loki
  labels:
    app: loki
spec:
  type: ClusterIP 
  ports:
    - name: loki
      protocol: TCP
      port: 3100
      targetPort: 3100
  selector:
      app: loki