repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: namespaces
    chart: ./chart/namespaces

  - name: pokemon-mysql
    chart: bitnami/mysql 
    namespace: mysql
    createNamespace: false
    needs:
      - external-secrets/external-secrets-extra
    values:
      - ./env/mysql.yaml  

  - name: external-secrets-extra
    namespace: external-secrets
    createNamespace: false
    chart: ./chart/external-secrets/extra

  - name: pokemon
    chart: ./chart/pokemon
    namespace: pokemon
    createNamespace: true
    needs:
      - mysql/pokemon-mysql
    values:
      - ./env/pokemon.yaml
      
  - name: pokemon-redis
    chart: bitnami/redis
    namespace: redis
    createNamespace: true
    values:
      - ./env/redis.yaml

  - name: pokemon-memcached
    chart: bitnami/memcached
    namespace: memcached
    createNamespace: true
    values:
      - ./env/memcached.yaml

  - name: monitoring-extra
    chart: ./chart/monitoring-extra
    namespace: monitoring
    needs:
      - external-secrets/external-secrets-extra
      - pokemon/pokemon
    createNamespace: false