
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gitlab-secret-store
spec:
  provider:
    # provider type: gitlab
    gitlab:
      #url: https://gitlab.com
      projectID: "65173083"
      auth:
        SecretRef:
          accessToken:
            name: gitlab-access-token
            namespace: external-secrets
            key: accessToken