apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pokemon-secret
  namespace: mysql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: pokemon-secret
    creationPolicy: Owner
  data:
    - secretKey: mysql-password
      remoteRef:
        key: MYSQL_PASSWORD
    - secretKey: mysql-root-password
      remoteRef:
        key: MYSQL_ROOT_PASSWORD
