apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.php.serviceName }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: php
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
    - name: php
      protocol: TCP
      port: {{ .Values.app.php.servicePort }}
      targetPort: {{ .Values.app.php.containerPort }}